services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - ${HOST_WEB_DIR}:/var/www/html
    networks:
      inception:
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    container_name: wp-php
    env_file:
      - .env
    secrets:
      - admin_pass
      - user_pass
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    networks:
      inception:
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    secrets:
      - mysql_user_pass
      - mysql_root_pass
    volumes:
      - db:/var/lib/mysql
    networks:
      inception:
    restart: unless-stopped
  
networks:
  inception:
    name: inception

secrets:
  admin_pass:
    file: ../secrets/admin_pass
  user_pass:
    file: ../secrets/user_pass
  mysql_root_pass:
    file: ../secrets/mysql_root_pass
  mysql_user_pass:
    file: ../secrets/mysql_user_pass

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_WEB_DIR}
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_DB_DIR}