services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - ${HOST_WEB_DIR}:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    container_name: wp-php
    env_file:
      - .env
    secrets:
      - admin_pass
      - user_pass
      - mysql_user_pass
    volumes:
      - ${HOST_WEB_DIR}:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    secrets:
      - mysql_root_pass
      - mysql_user_pass
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:

secrets:
  admin_pass:
    file: ${SECRETS_DIR}/admin_pass
  user_pass:
    file: ${SECRETS_DIR}/user_pass
  mysql_root_pass:
    file: ${SECRETS_DIR}/mysql_root_pass
  mysql_user_pass:
    file: ${SECRETS_DIR}/mysql_user_pass

volumes:
  db: