services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    container_name: wp-php
    env_file:
      - .env
    secrets:
      - admin_pass
      - user_pass
      - mysql_user_pass
    volumes:
      - web:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm8.2 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    secrets:
      - mysql_root_pass
      - mysql_user_pass
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  inception:

secrets:
  admin_pass:
    file: ${SECRETS_DIR}/admin_pass
  user_pass:
    file: ${SECRETS_DIR}/user_pass
  mysql_root_pass:
    file: ${SECRETS_DIR}/mysql_root_pass
  mysql_user_pass:
    file: ${SECRETS_DIR}/mysql_user_pass

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_DB_DIR}
  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_WEB_DIR}
