services:
  nginx:
    build: srcs/requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - /home/mlitvino/data/web:/var/www/html
    networks:
      inception:
    #restart: unless-stopped
  wordpress:
    build: srcs/requirements/wordpress
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - /home/mlitvino/data/web:/var/www/html
    networks:
      inception:
    #restart: unless-stopped
  mariadb:
    build: srcs/requirements/mariadb
    container_name: mariadb
    volumes:
      - ./db:/var/lib/mysql
      #- /home/mlitvino/data/db:/var/lib/mysql
    networks:
      inception:
    #restart: unless-stopped
networks:
  inception:
